project:
  type: website
  render:
    - "*.qmd"
    - "projects/"
    - "experience/"
    - "writings/"
    - "ontology/"
    - "!documents/"
    - "!_archive/"
    - "!addpage/"
    - "!python/"

website:
  title: "Harlan A Nelson"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: projects/index.qmd
        text: Projects
      - href: experience/index.qmd
        text: Experience
      - href: publications.qmd
        text: Publications
      - href: skills.qmd
        text: Skills
      - href: writings/index.qmd
        text: Writings
      - href: ontology/index.qmd
        text: Ontology
    right:
      - icon: linkedin
        href: https://www.linkedin.com/in/harlananelson/
      - icon: github
        href: https://github.com/harlananelson

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
